module.exports = {
	"baseUrl": "https://localhost:3000/",
	"siteName": "ETH_Simulator",
	"jwt_secret": "tradingsimulator123",
	"jwt_expire": "1d",
	"trading_symbol": "ETHUSD",
	"Discord_CLIENT_ID": "1055529634705444864",
	"Discord_CLIENT_SECRET": "EmgdHILyfNKcJM5PNM7N9i-3Pf7XUQmb",
	"Discord_redirect": "http://143.244.150.181/discord-auth",
	"Twitter_CLIENT_ID": "UkZWWFF3aDl5ajFjRm51ZnNkb2o6MTpjaQ",
	"Twitter_CLIENT_SECRET": "qK-TUmQCWvxBD1ybMxCxrTaCQztxHnZoJshjARABmSQIX0h4uL",
	"Twitter_redirect": "http://143.244.150.181/discord-auth",
	"CryptoConfig": [
		"BTCUSD",
		"ETHUSD",
		"BNBUSD",
		"XRPUSD",
		"DOGEUSD",
		"ADAUSD",
		"MATICUSD",
		"DOTUSD",
		"LTCUSD",
		"SOLUSD",
		"TRXUSD",
		"SHIBUSD",
		"UNIUSD",
		"AVAXUSD",
		"LINKUSD",
		"ATOMUSD",
		"XMRUSD",
		"XLMUSD",
		"ALGOUSD",
		"APEUSD",
		"XTZUSD",
		"AAVEUSD",
		"MANAUSD",
		"SANDUSD",
		"AXSUSD",
		"CAKEUSD",
	  ]
}